import type { Metadata } from "next";

import "./globals.css";
import NavLinks from "./components/nav-links";
import { ChakraProvider } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "I hate my job",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen flex-row antialiased`}>
        <ChakraProvider>
          <NavLinks />
          <main className="ml-[185px] flex-1">{children}</main>
        </ChakraProvider>
      </body>
    </html>
  );
}
